// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package blogger;


public class GetCategories {
    protected java.lang.String string_1;
    
    public GetCategories() {
    }
    
    public GetCategories(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
}
