// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package blogger;

public interface BloggerSEI extends java.rmi.Remote {
	public boolean login(java.lang.String string_1) throws java.rmi.RemoteException;

	public java.lang.String post(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, java.lang.String string_4, java.lang.String string_5) throws java.rmi.RemoteException;

	public java.lang.String getCategories(java.lang.String string_1) throws java.rmi.RemoteException;

	public java.lang.String getRating(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3) throws java.rmi.RemoteException;

	public java.lang.String postComment(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3) throws java.rmi.RemoteException;

	public java.lang.String postMedia(java.lang.String string_1) throws java.rmi.RemoteException;

	public java.lang.String retreive_blog(java.lang.String string_1, java.lang.String string_2) throws java.rmi.RemoteException;

	public java.lang.String retrieve_blogList(java.lang.String string_1, java.lang.String string_2) throws java.rmi.RemoteException;

	public java.lang.String setRating(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, int int_4) throws java.rmi.RemoteException;

}
