// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package blogger;


public class Post {
    protected java.lang.String string_1;
    protected java.lang.String string_2;
    protected java.lang.String string_3;
    protected java.lang.String string_4;
    protected java.lang.String string_5;
    
    public Post() {
    }
    
    public Post(java.lang.String string_1, java.lang.String string_2, java.lang.String string_3, java.lang.String string_4, java.lang.String string_5) {
        this.string_1 = string_1;
        this.string_2 = string_2;
        this.string_3 = string_3;
        this.string_4 = string_4;
        this.string_5 = string_5;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public java.lang.String getString_3() {
        return string_3;
    }
    
    public void setString_3(java.lang.String string_3) {
        this.string_3 = string_3;
    }
    
    public java.lang.String getString_4() {
        return string_4;
    }
    
    public void setString_4(java.lang.String string_4) {
        this.string_4 = string_4;
    }
    
    public java.lang.String getString_5() {
        return string_5;
    }
    
    public void setString_5(java.lang.String string_5) {
        this.string_5 = string_5;
    }
}
