// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package blogger;


public class Retrieve_blogListResponse {
    protected java.lang.String result;
    
    public Retrieve_blogListResponse() {
    }
    
    public Retrieve_blogListResponse(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getResult() {
        return result;
    }
    
    public void setResult(java.lang.String result) {
        this.result = result;
    }
}
