// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package blogger;


public class LoginResponse {
    protected boolean result;
    
    public LoginResponse() {
    }
    
    public LoginResponse(boolean result) {
        this.result = result;
    }
    
    public boolean isResult() {
        return result;
    }
    
    public void setResult(boolean result) {
        this.result = result;
    }
}
